server:
  port: 8081

kafka:
  consumer:
    topic: topic1
    id: test

spring:
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9094