server:
  port: 8081


kafka:
  bootstrap-servers: localhost:9092
  consumer:
    topic: topic1
    groupId: test.consumer
    containerName: testContainer

#logging:
#  level:
#    org.apache.kafka: DEBUG